use customer_behavior;
select * from customer;
-- What is the total revenue generated by male vs. female customers?


select gender, sum(purchase_amount) as revenue 
from customer 
group by gender;


-- Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount 
from customer 
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer);


-- Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(AVG(review_rating),2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;


-- Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, round(AVG(purchase_amount),2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;


-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select round(avg(purchase_amount),2) as average_purchase_amount
, subscription_status, sum(purchase_amount) as total_revenue,
count(*) as Total_customer
from customer 
group by subscription_status;


-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(sum( case when discount_applied = "Yes" then 1 else 0 end) * 100/count(*),2) as discount_purchases
from customer	
group by item_purchased
order by discount_purchases desc
limit 5;


--  Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select case when previous_purchases =  1 then 'new '
when previous_purchases between 1 and 10 then 'returning'
else 'loyal'end as "customer_segment",  count(*) as segment_count
from customer 
group by customer_segment;
-- What are the top 3 most purchased products within each category?

select category, item_purchased
from customer
group by category
order by previous_purchases desc
limit 3;

-- What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category 
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases> 5 
group by subscription_status;

-- What is the revenue contribution of each age group?
select sum(purchase_amount) as total_revenue, age_group
from customer
group by age_group
order by total_revenue desc

